#### Chi-Square Test

Example 1: Goodness-of-fit Test 
M&M anounced that the color breakdown of candy is 0.24, 0.20, 0.16, 0.14, 0.13, 0.13 for blue, orange, green, yellow, red, and brown.  

A statistician collected 712 M&Ms to test if Mars’ published M&M color breakdown was accurate. These were the color breakdown he found:  
18.7% blue  
18.7% orange  
19.5% green  
14.5% yellow  
15.1% red  
13.5% brown  
Please check if the sample is consistent with M&M's published breakdown.   

In [1]:
import numpy as np
from scipy import stats

# Observed values (converted from proportions)
observed = np.array([0.187 * 712, 0.187 * 712, 0.195 * 712, 0.145 * 712, 0.151 * 712, 0.135 * 712])

# Expected probabilities (must sum to 1)
expected_prob = np.array([0.24, 0.20, 0.16, 0.14, 0.13, 0.13])

# Convert expected probabilities into expected counts
expected = expected_prob * observed.sum()

# Perform Chi-Square Goodness-of-Fit Test
chi2_stat, p_value = stats.chisquare(f_obs=observed, f_exp=expected)

# Print results
print(f"Chi-Square Statistic: {chi2_stat:.4f}")
print(f"P-Value: {p_value:.4f}")


Chi-Square Statistic: 17.0656
P-Value: 0.0044


Example 2: Homogeneity Test

In [3]:
import pandas as pd

# Example contingency table (replace with actual data)
caith = np.array([
    [110, 45, 36],  # Row 1
    [67, 48, 22],   # Row 2
    [91, 71, 64],   # Row 3
])  

# Perform Chi-Square Test for Independence
chi2_stat, p_value, dof, expected = stats.chi2_contingency(caith)

# Print results
print(f"\nChi-Square Test for Contingency Table")
print(f"Chi-Square Statistic: {chi2_stat:.4f}")
print(f"P-Value: {p_value:.4f}")
print(f"Degrees of Freedom: {dof}")
print(f"Expected Frequencies:\n{expected}")



Chi-Square Test for Contingency Table
Chi-Square Statistic: 17.5625
P-Value: 0.0015
Degrees of Freedom: 4
Expected Frequencies:
[[ 92.39711191  56.54151625  42.06137184]
 [ 66.27436823  40.55595668  30.16967509]
 [109.32851986  66.90252708  49.76895307]]
